sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  apt: true
  directories:
    - $HOME/.stack/
    - .stack-work/

matrix:
  include:
    - env: STACK_YAML=stack-lts-6.yaml
    - env: STACK_YAML=stack-lts-8.yaml
    - env: STACK_YAML=stack-nightly.yaml

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack update
  - stack setup
  - stack install hlint

script:
  - ./Shakefile.hs sanity
