wolf:
  image: swift-nav/wolf:v0.1
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

decide:
  extends:
    file: docker-compose.yml
    service: wolf
  restart: always
  command: wolf-decide -c '/cfg/config.yaml' -p '/cfg/plan.yaml'
  volumes:
    - ./cfg:/cfg

hello:
  extends:
    file: docker-compose.yml
    service: wolf
  restart: always
  command: wolf-act -c '/cfg/config.yaml' -q 'hello-queue' -x '/cfg/hello.yaml'
  volumes:
    - ./cfg:/cfg
    - /tmp:/tmp
    - /var/run/docker.sock:/var/run/docker.sock

world:
  extends:
    file: docker-compose.yml
    service: wolf
  restart: always
  command: wolf-act -c '/cfg/config.yaml' -q 'world-queue' -x '/cfg/world.yaml'
  volumes:
    - ./cfg:/cfg
    - /tmp:/tmp
    - /var/run/docker.sock:/var/run/docker.sock
